Completed array-manipulation-3.
alexdenbaugh/c0321-code-solutions pull request #43
Opened 2021-03-22 07:01 UTC by alexdenbaugh

![array-manipulation-3](https://user-images.githubusercontent.com/78943990/111952033-b8385780-8aa1-11eb-9fd2-fa8456094c4e.PNG)

2021-03-29 22:01 UTC, codingcodymiller requested changes
Nice work so far!! Please see my notes

2021-03-29 22:01 UTC, codingcodymiller commented on array-manipulation-3/src/union.js
> +  }
Same feedback here! What if `first` includes multiple values that are the same? We only want one of each value in the new array to be returned.

2021-04-07 18:46 UTC, scbowler requested changes
Looking really good, a couple cleanup items needed. Let us know if you have any questions.

2021-04-07 18:46 UTC, scbowler commented on array-manipulation-3/src/flatten.js
> +      }
The extra check of checking the array length isn't necessary and has no net benefit.

2021-04-07 18:46 UTC, scbowler commented on array-manipulation-3/src/zip.js
> +    pairArray.push(second[i]);
You can pass multiple things to `.push`

For Example:
```JAVASCRIPT
pairArray.push('Item 1', 'Item 2', 'Item 3');
```

2021-04-07 22:00 UTC, scbowler approved these changes
Great job implementing the feedback, looks good! 👍

2021-04-07 22:23 UTC, merged