Completed object-manipulation-3.
alexdenbaugh/c0321-code-solutions pull request #44
Opened 2021-03-22 10:12 UTC by alexdenbaugh

![object-manipulation-3-1](https://user-images.githubusercontent.com/78943990/111974032-59340c00-8abc-11eb-9823-06f0d96553d7.PNG)
![object-manipulation-3-2](https://user-images.githubusercontent.com/78943990/111974039-5a653900-8abc-11eb-82c8-ef318dcb8765.PNG)

2021-03-29 22:06 UTC, codingcodymiller requested changes
Great start here, dude!! Please take a look at my feedback for some areas to address

2021-03-29 22:06 UTC, codingcodymiller commented on object-manipulation-3/main.js
> +  var maxNumber = Math.floor(cardDeck.length);
Why the `ceil` and `floor` here?

2021-03-29 22:06 UTC, codingcodymiller commented on object-manipulation-3/main.js
> +    if (!shuffledDeck.includes(cardDeck[randomNumber])) {
So does this loop just keep going until the loop manages to randomly get every card in the deck? That could take a long time. I would try to look into some ways you could just randomize the array. Make sure you understand how the code works, though!

2021-03-29 22:06 UTC, codingcodymiller commented on object-manipulation-3/main.js
> +  }
Is this to give each player their initial hand? You might be able to do this without the need for less moving pieces. You can just remove cards from the `shuffledDeck` as they get dealt, so you can always "deal" the same index.

2021-03-29 22:06 UTC, codingcodymiller commented on object-manipulation-3/main.js
> +      }
What about using an object that has a key for each card type, and a value of its card worth? That should simplify this by quite a bit.

2021-04-07 19:23 UTC, scbowler approved these changes
Great job implementing Cody's feedback, looks good! 👍 

When time permits I would recommend trying to re do this in OOP as an additional challenge.

2021-04-07 20:28 UTC, merged